QuickJSPP: JSNumericOperations Struct Reference
JSNumericOperations Struct Reference
Public Attributes
JSValue(* to_string)(JSContext *ctx, JSValueConst val)
JSValue(* from_string)(JSContext *ctx, const char *buf, int radix, int flags, slimb_t *pexponent)
int(* unary_arith)(JSContext *ctx, JSValue *pres, OPCodeEnum op, JSValue op1)
int(* binary_arith)(JSContext *ctx, OPCodeEnum op, JSValue *pres, JSValue op1, JSValue op2)
int(* compare)(JSContext *ctx, OPCodeEnum op, JSValue op1, JSValue op2)
JSValue(* mul_pow10_to_float64)(JSContext *ctx, const bf_t *a, int64_t exponent)
int(* mul_pow10)(JSContext *ctx, JSValue *sp)
Detailed Description
Definition at line 218 of file quickjs.c.
Member Data Documentation
to_string
JSValue(* JSNumericOperations::to_string) (JSContext *ctx, JSValueConst val)
Definition at line 219 of file quickjs.c.
from_string
JSValue(* JSNumericOperations::from_string) (JSContext *ctx, const char *buf, int radix, int flags, slimb_t *pexponent)
Definition at line 220 of file quickjs.c.
unary_arith
int(* JSNumericOperations::unary_arith) (JSContext *ctx, JSValue *pres, OPCodeEnum op, JSValue op1)
Definition at line 222 of file quickjs.c.
Referenced by JS_AddIntrinsicBigDecimal(), JS_AddIntrinsicBigFloat(), JS_AddIntrinsicBigInt(), js_not_slow(), js_unary_arith_slow(), and set_dummy_numeric_ops().
binary_arith
int(* JSNumericOperations::binary_arith) (JSContext *ctx, OPCodeEnum op, JSValue *pres, JSValue op1, JSValue op2)
Definition at line 224 of file quickjs.c.
Referenced by js_add_slow(), JS_AddIntrinsicBigDecimal(), JS_AddIntrinsicBigFloat(), JS_AddIntrinsicBigInt(), js_binary_arith_slow(), js_binary_logic_slow(), and set_dummy_numeric_ops().
compare
int(* JSNumericOperations::compare) (JSContext *ctx, OPCodeEnum op, JSValue op1, JSValue op2)
Definition at line 226 of file quickjs.c.
Referenced by JS_AddIntrinsicBigDecimal(), JS_AddIntrinsicBigFloat(), JS_AddIntrinsicBigInt(), js_eq_slow(), and js_relational_slow().
mul_pow10_to_float64
JSValue(* JSNumericOperations::mul_pow10_to_float64) (JSContext *ctx, const bf_t *a, int64_t exponent)
Definition at line 229 of file quickjs.c.
mul_pow10
int(* JSNumericOperations::mul_pow10) (JSContext *ctx, JSValue *sp)
Definition at line 231 of file quickjs.c.
Referenced by JS_AddIntrinsicBigFloat(), JS_CallInternal(), and set_dummy_numeric_ops().
The documentation for this struct was generated from the following file:
quickjs/quickjs.c